fix-small-problems
mikevo/uno-heterogeneous-knowledge pull request #92
Opened 2017-04-22 18:03 UTC by egemix

Closes #19 
#86 
#87 
#88 
#90

2017-04-24 14:18 UTC, kmaus commented on src/app/models/question.rb
> +	accepts_nested_attributes_for :answers, allow_destroy: true
Why were these changes made? The lambda prevented blank questions from existing, and the `dependent => destroy` said that if the question is deleted, delete its answers as well.

2017-04-24 14:22 UTC, kmaus commented on src/app/models/quiz.rb
> +  has_many :questions
Why were these changes made? The lambda prevented blank questions from existing, and the `dependent => destroy` said that if the quiz is deleted, delete its questions as well.

2017-04-24 14:26 UTC, kmaus commented on src/db/migrate/20170322061738_add_quiz_to_question.rb
> -end
@mikevo am I right to think that deleting migration files is bad for the db?

2017-04-24 14:32 UTC, mikevo commented
deleting a migration file is bad for newly setting up the db, and whenever someone has already done this migration.

so yes, never ever delete a migration file. making a new one and changing the current db setup (all previous migrations are applied) is the way to go.

2017-04-24 23:13 UTC, mikevo requested changes
I think this PR needs a little love before it is ready to go into master.

2017-04-24 23:13 UTC, mikevo commented on src/app/controllers/courses_controller.rb
> +  authorize_resource :class => false
Why do you need to change this?

2017-04-24 23:13 UTC, mikevo commented on src/app/controllers/courses_controller.rb
> +  end
please modify your IDE to use the correct indent type (.editorconfig contains the config) such changes should not happen

2017-04-24 23:13 UTC, mikevo commented on src/app/controllers/add_quiz_id_to_questions_controller.rb
> +end
What does this controller? The name sounds like a migration file which does not need a controller. If this is the case remove it including all other stuff that is not needed

2017-04-24 23:13 UTC, mikevo commented on src/app/controllers/quizzes_controller.rb
> +
i guess this is the wrong indent again

2017-04-24 23:13 UTC, mikevo commented on src/app/controllers/quizzes_controller.rb
> +
Are you sure that this way of doing it will work out in the end because it differs from the purposed way that we talked about in some of the team meetings on Wednesdays.

2017-04-24 23:13 UTC, mikevo commented on src/app/controllers/users_controller.rb
> +    params.require(:user).permit(:email, :password, :password_confirmation, :username, :role)
Why is this change necessary? I think we do not want to accept the role form the UI in general.

2017-04-24 23:13 UTC, mikevo commented on src/app/models/course.rb
> -	has_many :quizzes, :dependent => :destroy
Why should we keep the quizzes if the course gets destroyed?

2017-04-24 23:13 UTC, mikevo commented on src/app/models/question.rb
> +	accepts_nested_attributes_for :answers, allow_destroy: true
I agree with @kmaus this was fine before. In future please ask before doing such changes.

2017-04-24 23:13 UTC, mikevo commented on src/app/views/courses/_form.html.erb
>  <% end %>
Editor indent!

2017-04-24 23:13 UTC, mikevo commented on src/app/views/courses/index.html.erb
>  </div>
Editor indent

2017-04-24 23:13 UTC, mikevo commented on src/db/migrate/20170322061637_create_questions.rb
> +      t.string :question
This is the reason why some tests and the build are failing.

Never ever change a migration file that is in the master!

2017-04-24 23:13 UTC, mikevo commented on src/db/migrate/20170322061637_create_questions.rb
> +    add_reference :questions, :quizzes, index: true
Change here in the wrong place! make a new migration file if necessary

2017-04-24 23:13 UTC, mikevo commented on src/db/migrate/20170322061700_create_answers.rb
> +    add_reference :answers, :questions, index: true
Changes are not allowed here. Make a new migration file.

2017-04-24 23:13 UTC, mikevo commented on src/db/migrate/20170322061905_add_question_to_answer.rb
> -end
Not allowed! New migration file.

2017-04-24 23:13 UTC, mikevo commented on src/db/migrate/20170422014256_add_question_id_to_answers.rb
> +end
Questions and answers are already linked in the db so why linking them again?

2017-04-24 23:13 UTC, mikevo commented on src/db/migrate/20170422014344_add_quiz_id_to_question.rb
> +end
Quizzes and questions are already linked in the db so why do you want to link them again?

2017-04-24 23:13 UTC, mikevo commented on src/db/seeds.rb
> +Quiz.create! title: "Computer Science ", course_id: course.id
Why should we add  these things to a production environment? The admin user is intended to bootstrap the whole sys like a root user in unix.

The rest should go into test/fixtures if you need them for your (unit) tests.

2017-04-24 23:13 UTC, mikevo commented on src/test/controllers/add_quiz_id_to_questions_controller_test.rb
> +end
Is there a reason for adding this test and its controller?
I guess this was generated with the migration and should be removed.

2017-04-24 23:13 UTC, mikevo commented on src/test/models/result_test.rb
> +  #   assert true
There should be something in here

2017-04-24 23:13 UTC, mikevo commented on src/test/models/add_quiz_id_to_question_test.rb
> +  #   assert true
This does not test anything -> useless

2017-04-26 19:25 UTC, mikevo commented on src/app/models/quiz.rb
> -  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
I think wee need those two lines

2017-04-26 20:08 UTC, mikevo approved these changes

2017-04-28 20:45 UTC, merged